name: Locust summary for locust-test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Locust summary
        uses: simiotics/locust-action@summary-output
        id: locust
        with:
          format: html-github
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.locust.outputs.summary }}',
            })
